site_name: すごい技術のサイト
title: 技術がすごい
description: とにかくすごい技術
keywords: ['すごい', '技術']
url: https://butchi.github.io/htjs/
facebook_app_id": '903742642995033'
ogp_image_url: http://butchi.github.io/htjs/ogp.png
ogp_image_width: 128
ogp_image_height: 128
