import { getHastElement, tagNameArr } from "./htjs.mjs"

const htmlElement = []

tagNameArr.forEach((tagName) => {
    if (tagName === "map") tagName = "mapTag"
    htmlElement[tagName] = (_txtArr, ...attrArr) => getHastElement(tagName, attrArr)
});

export default function htjsParse(options) {
    const parser = (doc) => {
        const {
            a,
            abbr,
            address,
            area,
            article,
            aside,
            audio,
            b,
            base,
            bdi,
            bdo,
            blockquote,
            body,
            br,
            button,
            canvas,
            caption,
            cite,
            code,
            col,
            colgroup,
            command,
            datalist,
            dd,
            del,
            details,
            dfn,
            div,
            dl,
            dt,
            em,
            embed,
            fieldset,
            figcaption,
            figure,
            footer,
            form,
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
            head,
            header,
            hr,
            html,
            i,
            iframe,
            img,
            input,
            ins,
            kbd,
            keygen,
            label,
            legend,
            li,
            link,
            main,
            mark,
            menu,
            meta,
            meter,
            nav,
            noscript,
            object,
            ol,
            optgroup,
            option,
            output,
            p,
            param,
            pre,
            progress,
            q,
            rp,
            rt,
            ruby,
            s,
            samp,
            script,
            section,
            select,
            small,
            source,
            span,
            strong,
            style,
            sub,
            summary,
            sup,
            table,
            tbody,
            td,
            textarea,
            tfoot,
            th,
            thead,
            time,
            title,
            tr,
            track,
            u,
            ul,
            video,
            wbr,
        } = htmlElement

        const varTag = htmlElement.var

        return eval(doc)
    }

    Object.assign(this, { Parser: parser })
}
